{
 "title": "Vendor License Feature Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vendor_name",
    "query": {
     "query": "label_values(feature_active_count,vendor_name)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(feature_active_count{vendor_name=\"$vendor_name\"},server)"
    }
   },
   {
    "name": "feature",
    "query": {
     "query": "label_values(feature_active_count{vendor_name=\"$vendor_name\"},feature)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Feature Inuse Count Per User",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "feature_inuse_count_peruser_total{vendor_name=\"$vendor_name\", server=\"$server\", feature=~\"$feature\"} ",
     "legendFormat": "{{username}}-{{feature}}"
    }
   ]
  },
  {
   "title": "License Feature Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "feature_active_count{application=\"flexnetlicensemonitor\", vendor_name=\"$vendor_name\", server=\"$server\", feature=~\"$feature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "License Feature Count Remain",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "feature_active_count{application=\"flexnetlicensemonitor\", vendor_name=\"$vendor_name\", server=\"$server\", feature=~\"$feature\"}"
    },
    {
     "expr": "feature_inuse_count{application=\"flexnetlicensemonitor\", vendor_name=\"$vendor_name\", server=\"$server\", feature=~\"$feature\"} "
    }
   ]
  },
  {
   "title": "All License Feature Count Remain Asc",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "feature_active_count{application=\"flexnetlicensemonitor\", vendor_name=\"$vendor_name\", server=\"$server\"}"
    },
    {
     "expr": "feature_inuse_count{application=\"flexnetlicensemonitor\", vendor_name=\"$vendor_name\", server=\"$server\"} "
    }
   ]
  },
  {
   "title": "Feature Inuse Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "feature_inuse_count{vendor_name=\"$vendor_name\", server=\"$server\", feature=~\"$feature\"} ",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Feature Queue Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "feature_queue_count{vendor_name=\"$vendor_name\", server=\"$server\", feature=~\"$feature\"} ",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Feature Inuse Duratrion",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "time() - feature_inuse_startts{application=\"flexnetlicensemonitor\", vendor_name=\"$vendor_name\", server=\"$server\", feature=~\"$feature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "License Feature Expire Time",
   "type": "table",
   "description": "<14d(error)\n<30d(warning)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "feature_expires{application=\"flexnetlicensemonitor\", feature=~\"$feature\", vendor_name=\"$vendor_name\", server=\"$server\"} * 1000"
    },
    {
     "expr": "feature_expires{application=\"flexnetlicensemonitor\", feature=~\"$feature\", vendor_name=\"$vendor_name\", server=\"$server\"} - time()"
    }
   ]
  }
 ]
}