apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexnetlicensemonitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flexnetlicensemonitor
  template:
    metadata:
      labels:
        app: flexnetlicensemonitor
    spec:
      containers:
        - name: flexnetlicensemonitor
          image: pyflexnetlicensemonitor
          ports:
            - containerPort: 27777
          imagePullPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: flexnetlicensemonitor-service
spec:
  selector:
    app: flexnetlicensemonitor
  ports:
    - name:  http
      protocol: TCP
      port: 27777
      targetPort: 27777
